### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by EvoSems** [ShotokanZH/MiWiFi_Mesh_Node_Adder#6]
Hi mate. love you! recently got a 2nd mesh and cannot remember how to do all this.

using latest Mac OS but hit a road bump.

```
Evo@MacBook-Pro MiWiFi_Mesh_Node_Adder-main % python3 addmesh.py   
Traceback (most recent call last):
  File "/Users/Evo/Downloads/MiWiFi_Mesh_Node_Adder-main/addmesh.py", line 7, in <module>
    import requests
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/__init__.py", line 11, in <module>
    from . import exceptions
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/exceptions.py", line 3, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

any updates needed to get this working?

thanks in advance

**Comment by ShotokanZH** [comment]
Hi!
What's the output when you try to run:
`python3 -m pip install -r requirements.txt`
?

And what happens if you try to install six directly?
`python3 -m pip install six`

P.s. seems related to:
https://github.com/Datalux/Osintgram/issues/947#issuecomment-1872485426

**Comment by EvoSems** [comment]
Hi mate. just came back to revoke the above. I switched to a different MacBook which I haven't installed much on. script worked perfectly!

I have a AX3200 and just got the new AX7000, I didn't get the AIot scan to work but manually added the MAC address and it says Node configured Correctly! 

just waiting now to see if it shows up as a mesh. it hasn't yet but its been only 5 mins.

**Comment by EvoSems** [comment]
actually didn't add. so I have swapped the order. 7000 --> 3600 but the script has authentication failed when trying to log in...

reason. the 7000 shows the dual 2.4/5ghz at factory setup. the 3600 has both available separately

**Comment by ShotokanZH** [comment]
I'm guessing the ax7000 has a different set of APIs for that or does not support mesh with the ax3600 entirely

Are the two devices close to each other? For the first config they need to be

**Comment by ShotokanZH** [comment]
https://github.com/scientifichackers/pymiwifi/pull/2

The new devices switched login encryption entirely, that might be one of the reasons, I would look into that but I am not using the Xiaomi firmware anymore (the ax3600 is officially supported in openwrt)
